FROM alpine:latest

RUN apk update && \
  apk add python3 py3-pip && \
  pip3 install --upgrade pip && \
  pip3 install --upgrade virtualenv && \
  apk add gcc musl-dev python3-dev libffi-dev openssl-dev krb5-dev rust cargo && \
  pip3 install pywinrm && \
  pip3 install ansible && \
  pip3 install requests-credssp && \
  apk add bash && \
  apk add freetds-dev && \
  pip install pymssql && \
  ansible-galaxy collection install community.windows && \
  rm -rf /var/cache/apk/* && \
  mkdir /local

WORKDIR /local